{'status': 'ok', 'totalResults': 881, 'articles': [
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'F vs. TSLA: Which Stock Should Value Investors Buy Now?',
     'description': 'F vs. TSLA: Which Stock Is the Better Value Option?',
     'url': 'http://www.zacks.com/stock/news/1847226/f-vs-tsla-which-stock-should-value-investors-buy-now?cid=CS-ENTREPRENEUR-FT-tale_of_the_tape|yseop_template_3-1847226',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-411440.jpeg',
     'publishedAt': '2022-01-04T16:40:11Z',
     'content': 'Investors with an interest in Automotive - Domestic stocks have likely encountered both Ford Motor Company (F) and Tesla (TSLA). But which of these two stocks offers value investors a better bang for… [+2788 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Nalak Das',
     'title': '6 Must-Buy Large-Cap Stocks Ahead of Q4 Earnings Next Week',
     'description': 'Six large-cap companies will report earnings next week. These are: TSLA, URI, FCX, VRTX, STLD and BRO.',
     'url': 'http://www.zacks.com/stock/news/1855187/6-must-buy-large-cap-stocks-ahead-of-q4-earnings-next-week?cid=CS-ENTREPRENEUR-FT-analyst_blog|investment_ideas-1855187',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-414380.jpeg',
     'publishedAt': '2022-01-21T11:50:00Z',
     'content': 'Wall Street is facing severe volatility in this week as market participants are keeping their fingers crossed for a hawkish Fed in the near term. However, the fourth-quarter 2021 earnings season is g… [+8901 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'Why We Expect Tesla (TSLA) to Deliver Q4 Earnings Beat',
     'description': "Robust demand for Model 3/Y and stellar performance of the solar arm are likely to buoy Tesla's (TSLA) Q4 earnings.",
     'url': 'http://www.zacks.com/stock/news/1854724/why-we-expect-tesla-tsla-to-deliver-q4-earnings-beat?cid=CS-ENTREPRENEUR-FT-analyst_blog|earnings_preview-1854724',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-414200.jpeg',
     'publishedAt': '2022-01-20T15:51:00Z',
     'content': 'Tesla\xa0TSLA is set to release fourth-quarter 2021 results on Jan 26, after the closing bell. The Zacks Consensus Estimate for the to-be-reported quarters earnings and revenues is pegged at $2.02 per s… [+5392 chars]'},
    {'source': {'id': None, 'name': 'Blogspot.com'}, 'author': 'noreply@blogger.com (Unknown)',
     'title': "Apple has become the world's first $3 trillion company",
     'description': '<table><tr><td></td></tr><tr><td>Apple CEO Tim Cook greets fans outside the Apple Store on Fifth Ave in the Manhattan borough of New York, New York, U.S., September 20, 2019. REUTERS/Carlo Allegri</td></tr>\r\n</table>Apple has taken another important step. The…',
     'url': 'https://techncruncher.blogspot.com/2022/01/apple-has-become-worlds-first-3.html',
     'urlToImage': 'https://blogger.googleusercontent.com/img/a/AVvXsEgyPP0r5mnI0jk5fJKgCWYimbdTkN2oQfpu23mygLSRB3r7ahTGrxoYTqg_DUJpNYeOKjqoTPNX8kK525Rx8kGPPd1L8VNZpOKi3J0OgDgCUHoav40YrKcFbRXBdI9JLYhgtuARUEXO8PRx6rewnToOyCH-M5xbANJg88-b3bVMqEFULr3lSVIDNlJIXQ=w1200-h630-p-k-no-nu',
     'publishedAt': '2022-01-03T21:41:00Z',
     'content': 'Apple has taken another important step. The iPhone maker surpassed a market value of $ 3 trillion on Monday - the first publicly traded company\xa0 to be worth that much.\xa0Apple shares (AAPL)\xa0 briefly ro… [+1000 chars]'},
    {'source': {'id': None, 'name': 'StockNews.com'}, 'author': 'Oleksandr Pylypenko',
     'title': 'Tesla vs. Fisker: Which Electric Vehicle Stock is a Better Buy?',
     'description': "Today I'll analyze and compare Tesla (TSLA) and Fisker (FSR) to determine which electric vehicle (EV) stock is currently the better investment.",
     'url': 'https://stocknews.com/news/tsla-fsr-tesla-vs-fisker-which-electric-vehicle-stock-is-a-better-22244276/',
     'urlToImage': 'https://assets.entrepreneur.com/providers/stocknews/hero-image-stocknews-413951.jpeg',
     'publishedAt': '2022-01-19T15:08:58Z',
     'content': "Today I'll analyze and compare Tesla (TSLA) and Fisker (FSR) to determine which electric vehicle (EV) stock is currently the better investment.\r\nshutterstock.com - StockNews\r\nThe electric vehicle (EV… [+5361 chars]"},
    {'source': {'id': None, 'name': 'Blogspot.com'}, 'author': 'noreply@blogger.com (Unknown)',
     'title': 'China to cut new energy vehicle subsidies by 30% in 2022',
     'description': '<table><tr><td></td></tr><tr><td>Image Credit: REUTERS/Aly Song</td></tr>\r\n</table>China will cut subsidies for New Energy Vehicles (NEVs) such as electric cars by 30% in 2022 and withdraw them all by the end of the year, the Treasury Department said on its w…',
     'url': 'https://techncruncher.blogspot.com/2022/01/china-to-cut-new-energy-vehicle.html',
     'urlToImage': 'https://blogger.googleusercontent.com/img/a/AVvXsEjY0F15vlHrmq7rI1IjmrbaWejWHgtUaF3cIrf8cm0XfKBXPPd4WXs67V7Zpb0dSPSSzwT6Eh8pPvf2XBfV3HJ4-O4Sx6BuBhfkE8mE3i-IkLYjTUujSyKoYE_Bjd7vnXHn6TgBz-9f1T5uQRj9Mznvwxf5uHp5OAi1nwhLdmKPxusYovQET6MDsgBHKA=w1200-h630-p-k-no-nu',
     'publishedAt': '2022-01-02T19:30:00Z',
     'content': 'China will cut subsidies for New Energy Vehicles (NEVs) such as electric cars by 30% in 2022 and withdraw them all by the end of the year, the Treasury Department said on its website.\xa0The subsidies f… [+1114 chars]'},
    {'source': {'id': 'reuters', 'name': 'Reuters'}, 'author': None,
     'title': 'BUZZ Tesla charged up after record deliveries, other EV stocks also rise - Reuters',
     'description': '** Shares of EV maker Tesla Inc <a href="https://www.reuters.com/companies/TSLA.O" target="_blank">(TSLA.O)</a> jump 9.35% to $1,155.55, set for best day since October',
     'url': 'https://www.reuters.com/markets/asia/buzz-tesla-charged-up-after-record-deliveries-other-ev-stocks-also-rise-2022-01-03/',
     'urlToImage': 'https://www.reuters.com/pf/resources/images/reuters/reuters-default.png?d=66',
     'publishedAt': '2022-01-03T16:00:00Z',
     'content': "** Shares of EV maker Tesla Inc (TSLA.O) jump 9.35% to $1,155.55, set for best day since October\r\n** TSLA reports record Q4 deliveries of 308,600 vehicles, well above analysts' estimates of 263,026 v… [+1336 chars]"},
    {'source': {'id': None, 'name': 'StockNews.com'}, 'author': 'Priyanka Mandal',
     'title': 'The 5 Best Performing Pure Play Electric Vehicle Stocks of 2021',
     'description': "The electric vehicle (EV) industry is expected to dominate the automotive industry over the next couple of decades, with increasing support from governments and consumers' growing uptake. Furthermore, rising crude...",
     'url': 'https://stocknews.com/news/tsla-lcid-xpev-li-fsr-the-5-best-performing-pure-play-electric-vehicle-stocks-of/',
     'urlToImage': 'https://assets.entrepreneur.com/providers/stocknews/hero-image-stocknews-411443.jpeg',
     'publishedAt': '2022-01-04T17:40:01Z',
     'content': "The electric vehicle (EV) industry is expected to dominate the automotive industry over the next couple of decades, with increasing support from governments and consumers' growing uptake. Furthermore… [+7725 chars]"},
    {'source': {'id': None, 'name': 'StockNews.com'}, 'author': 'Jaimini Desai',
     'title': 'Electric Vehicle Industry Report for 2022',
     'description': 'Sales of electric vehicles (EVs) have been skyrocketing and forecasts predict that sales will exponentially grow over the next decade. As a result, EV stocks, such as NIO (NIO) and...',
     'url': 'https://stocknews.com/news/tsla-gm-f-nio-bidu-rivn-electric-vehicle-industry-report-for-2022/',
     'urlToImage': 'https://assets.entrepreneur.com/providers/stocknews/hero-image-stocknews-410506.jpeg',
     'publishedAt': '2021-12-28T23:20:50Z',
     'content': 'Sales of electric vehicles (EVs) have been skyrocketing and forecasts predict that sales will exponentially grow over the next decade. As a result, EV stocks, such as NIO (NIO) and Tesla(TSLA) have b… [+17447 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'Market Futures Lower Ahead of Opening', 'description': 'Market Futures Lower Ahead of Opening',
     'url': 'http://www.zacks.com/stock/news/1856208/market-futures-lower-ahead-of-opening?cid=CS-ENTREPRENEUR-FT-economic_highlights-1856208',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-414763.jpeg',
     'publishedAt': '2022-01-24T15:47:00Z',
     'content': 'Mondays in late January can often bring harsh realities, depending on where in the U.S. you live, but the stock market is bringing the harshness to even the most pleasing of climates this morning. Th… [+2740 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Mark Vickery',
     'title': 'More of the Same to Start a New Trading Week',
     'description': 'The sell-off continues, rolling back the market exuberance felt in the final months of 2021.',
     'url': 'http://www.zacks.com/stock/news/1856198/more-of-the-same-to-start-a-new-trading-week?cid=CS-ENTREPRENEUR-FT-ahead_of_wall_street-1856198',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-414765.jpeg',
     'publishedAt': '2022-01-24T15:39:00Z',
     'content': 'Monday, January 24, 2022Mondays in late January can often bring harsh realities, depending on where in the U.S. you live, but the stock market is bringing the harshness to even the most pleasing of c… [+2981 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Sweta Killa',
     'title': "ETFs to Drive Tesla's Near $1 Million Vehicle Deliveries",
     'description': 'Annual deliveries surged 87% year over year to 936,172 vehicles, marking the fastest pace of growth in many years.',
     'url': 'http://www.zacks.com/stock/news/1846633/etfs-to-drive-tesla-s-near-1-million-vehicle-deliveries?cid=CS-ENTREPRENEUR-FT-etf_news_and_commentary-1846633',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-411245.jpeg',
     'publishedAt': '2022-01-03T17:15:00Z',
     'content': 'Tesla Motors TSLA reported another quarter of record deliveries, underscoring its strong growth and defying the global automotive semiconductor shortage that is hampering car production across the gl… [+5767 chars]'},
    {'source': {'id': None, 'name': "Investor's Business Daily"}, 'author': "Investor's Business Daily",
     'title': "Tesla Stock Rises As China Sales Topped 70,000 In December - Investor's Business Daily",
     'description': "<ol><li>Tesla Stock Rises As China Sales Topped 70,000 In December\xa0\xa0Investor's Business Daily\r\n</li><li>Tesla sold a record 70847 China-made vehicles in December\xa0\xa0The Globe and Mail\r\n</li><li>Tesla posts record numbers in China by selling 70,602 vehicles loca…",
     'url': 'https://www.investors.com/news/tesla-stock-china-sales-topped-70000-in-december/',
     'urlToImage': 'https://www.investors.com/wp-content/uploads/2021/11/Stock-Tesla-charging-company.jpg',
     'publishedAt': '2022-01-11T13:56:00Z',
     'content': 'The China Passenger Car Association reported booming December electric vehicle sales on Tuesday, with record Tesla (TSLA) local deliveries. Tesla stock fell Tuesday morning, while China EV rivals ros… [+3349 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'The Zacks Analyst Blog Highlights: Tesla Inc., Steel Dynamics Inc., United Rentals Inc., Freeport-McMoRan Inc. and Vertex Pharmaceuticals Inc.',
     'description': 'Tesla Inc., Steel Dynamics Inc., United Rentals Inc., Freeport-McMoRan Inc. and Vertex Pharmaceuticals Inc. are included in this blog.',
     'url': 'http://www.zacks.com/stock/news/1856261/the-zacks-analyst-blog-highlights-tesla-inc-steel-dynamics-inc-united-rentals-inc-freeport-mcmoran-inc-and-vertex-pharmaceuticals-inc?cid=CS-ENTREPRENEUR-FT-press_releases-1856261',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-414794.jpeg',
     'publishedAt': '2022-01-24T16:44:00Z',
     'content': 'For Immediate Release\r\nChicago, IL January 24, 2022 Zacks.com announces the list of stocks featured in the Analyst Blog. Every day the Zacks Equity Research analysts discuss the latest news and event… [+10172 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'Ford (F) & ADT to Bolster Car Security With Canopy Venture',
     'description': 'Ford (F) to join forces with ADT to form a new venture called Canopy that will strengthen vehicle security.',
     'url': 'http://www.zacks.com/stock/news/1853738/ford-f-adt-to-bolster-car-security-with-canopy-venture?cid=CS-ENTREPRENEUR-FT-analyst_blog|company_news_-_corporate_actions-1853738',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-413891.jpeg',
     'publishedAt': '2022-01-19T12:45:00Z',
     'content': 'FordF recently announced that it will team up with the security company ADT Inc. to form a new joint venture (JV) named Canopy, which will offer vehicle security systems as an aftermarket product.For… [+7084 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Sanghamitra Saha',
     'title': "Is ARK's Stellar Run Over? 5 ETF Themes to Follow Cathie Wood",
     'description': "Though Cathie Wood's Ark Investment???s star products underperformed in 2021 and may continue to lag the broader market in 2022, Wood's fans may follow these ETF strategies to capitalize on...",
     'url': 'http://www.zacks.com/stock/news/1845146/is-ark-s-stellar-run-over-5-etf-themes-to-follow-cathie-wood?cid=CS-ENTREPRENEUR-FT-etf_news_and_commentary-1845146',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-410691.jpeg',
     'publishedAt': '2021-12-29T19:30:00Z',
     'content': 'Cathie Wood, famous for the success of Ark Investments winning products, has created a great fan following so far. Many want to follow her investing style as it has managed a spot among the top 10 is… [+5404 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'Should First Trust NASDAQ100 Equal Weighted ETF (QQEW) Be on Your Investing Radar?',
     'description': 'Style Box ETF report for QQEW',
     'url': 'http://www.zacks.com/stock/news/1848163/should-first-trust-nasdaq100-equal-weighted-etf-qqew-be-on-your-investing-radar?cid=CS-ENTREPRENEUR-FT-style_box_etf-1848163',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-411791.jpeg',
     'publishedAt': '2022-01-06T11:20:12Z',
     'content': "If you're interested in broad exposure to the Large Cap Growth segment of the US equity market, look no further than the First Trust NASDAQ100 Equal Weighted ETF (QQEW), a passively managed exchange … [+4960 chars]"},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'Should Invesco Dynamic Large Cap Growth ETF (PWB) Be on Your Investing Radar?',
     'description': 'Style Box ETF report for PWB',
     'url': 'http://www.zacks.com/stock/news/1845834/should-invesco-dynamic-large-cap-growth-etf-pwb-be-on-your-investing-radar?cid=CS-ENTREPRENEUR-FT-style_box_etf-1845834',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-410944.jpeg',
     'publishedAt': '2021-12-31T11:20:10Z',
     'content': 'Designed to provide broad exposure to the Large Cap Growth segment of the US equity market, the Invesco Dynamic Large Cap Growth ETF (PWB) is a passively managed exchange traded fund launched on 03/0… [+4417 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'Is SPDR NYSE Technology ETF (XNTK) a Strong ETF Right Now?',
     'description': 'Smart Beta ETF report for XNTK',
     'url': 'http://www.zacks.com/stock/news/1854406/is-spdr-nyse-technology-etf-xntk-a-strong-etf-right-now?cid=CS-ENTREPRENEUR-FT-smart_beta_etf-1854406',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-414116.jpeg',
     'publishedAt': '2022-01-20T11:20:10Z',
     'content': 'Launched on 09/25/2000, the SPDR NYSE Technology ETF (XNTK) is a smart beta exchange traded fund offering broad exposure to the Technology ETFs category of the market.\r\n - Zacks\r\nWhat Are Smart Beta … [+5154 chars]'},
    {'source': {'id': None, 'name': 'Zacks.com'}, 'author': 'Zacks Equity Research',
     'title': 'Is Invesco S&P 500 Equal Weight ETF (RSP) a Strong ETF Right Now?',
     'description': 'Smart Beta ETF report for RSP',
     'url': 'http://www.zacks.com/stock/news/1853686/is-invesco-s-p-500-equal-weight-etf-rsp-a-strong-etf-right-now?cid=CS-ENTREPRENEUR-FT-smart_beta_etf-1853686',
     'urlToImage': 'https://assets.entrepreneur.com/providers/zacks/hero-image-zacks-413878.jpeg',
     'publishedAt': '2022-01-19T11:20:10Z',
     'content': 'Designed to provide broad exposure to the Style Box - Large Cap Blend category of the market, the Invesco S&amp;P 500 Equal Weight ETF (RSP) is a smart beta exchange traded fund launched on 04/24/200… [+5056 chars]'}]}
